version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=services.settings
    depends_on:
      - db
    command: bash -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 services.wsgi:application"

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: myapp_db
      POSTGRES_USER: myapp_user
      POSTGRES_PASSWORD: myapp_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
