name: CI

on: [push, pull_request]

jobs:
  service-unit-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: service

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Build and run Docker Compose
      run: |
         dir
         docker-compose up -d

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        cd services
        python manage.py test
